name: Test Django REST API

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Django REST API
        env:
          DATA_LACITY_APP_TOKEN: ${{ secrets.DATA_LACITY_APP_TOKEN }}
          LA_CITY_BUSINESSES_API: https://data.lacity.org/resource/6rrh-rzua.json
        run: |
          cd backend
          coverage run --source='.' manage.py test active_businesses
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
